name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: List dist directory
        run: ls -la dist/
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/better-cards.js
          generate_release_notes: true
          draft: false
          prerelease: false